stages:
  - build
  - deploy

build-docker-image:
  stage: build
  image: docker
  services:
    - docker:dind #服務名稱是 docker，並且正在使用 Docker in Docker（dind）容器。Docker in Docker 允許你在一個容器中運行另一個 Docker 守護程序，這對於構建和測試容器非常有用。
  before_script:
    - docker login -u "joshua881117" -p ${DOCKER_HUB_TOKEN}
  script:
    - make build-image
    - make push-image
  tags:
    - build_image
  only:
    - tags

