version: '3'
services:
  minio:
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - ~/minio/data:/data
    environment:
      - MINIO_ROOT_USER=MINIOS3BUCKETROOT123
      - MINIO_ROOT_PASSWORD=apuxt9Xbmx6AUqj8QwkLU1Tjt1RzqsF4bMUBNrnE
    networks:
      - airflow_network
    command: server /data --console-address ":9090"

networks:
  airflow_network:
    external: true